import { ChatContextProvider } from "@/context/ChatContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Junye ChatApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChatContextProvider>
        <body className={inter.className}>{children}</body>
      </ChatContextProvider>
    </html>
  );
}
